# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_switch_action.ui'
#
# Created: Wed Mar 11 21:14:28 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_SwitchAction(object):
    def setupUi(self, SwitchAction):
        SwitchAction.setObjectName(_fromUtf8("SwitchAction"))
        SwitchAction.resize(502, 273)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SwitchAction.sizePolicy().hasHeightForWidth())
        SwitchAction.setSizePolicy(sizePolicy)
        self.gridLayoutWidget = QtGui.QWidget(SwitchAction)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 481, 251))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.contacts_state = QtGui.QGroupBox(self.gridLayoutWidget)
        self.contacts_state.setObjectName(_fromUtf8("contacts_state"))
        self.gridLayoutWidget_2 = QtGui.QWidget(self.contacts_state)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 30, 101, 211))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.contacts_state_l1_label = QtGui.QLabel(self.gridLayoutWidget_2)
        self.contacts_state_l1_label.setAlignment(QtCore.Qt.AlignCenter)
        self.contacts_state_l1_label.setObjectName(_fromUtf8("contacts_state_l1_label"))
        self.gridLayout_2.addWidget(self.contacts_state_l1_label, 0, 0, 1, 1)
        self.contacts_state_l2_label = QtGui.QLabel(self.gridLayoutWidget_2)
        self.contacts_state_l2_label.setAlignment(QtCore.Qt.AlignCenter)
        self.contacts_state_l2_label.setObjectName(_fromUtf8("contacts_state_l2_label"))
        self.gridLayout_2.addWidget(self.contacts_state_l2_label, 1, 0, 1, 1)
        self.contacts_state_l3_label = QtGui.QLabel(self.gridLayoutWidget_2)
        self.contacts_state_l3_label.setAlignment(QtCore.Qt.AlignCenter)
        self.contacts_state_l3_label.setObjectName(_fromUtf8("contacts_state_l3_label"))
        self.gridLayout_2.addWidget(self.contacts_state_l3_label, 2, 0, 1, 1)
        self.contacts_state_l1_frame = QtGui.QFrame(self.gridLayoutWidget_2)
        self.contacts_state_l1_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.contacts_state_l1_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.contacts_state_l1_frame.setObjectName(_fromUtf8("contacts_state_l1_frame"))
        self.gridLayout_2.addWidget(self.contacts_state_l1_frame, 0, 1, 1, 1)
        self.contacts_state_l2_frame = QtGui.QFrame(self.gridLayoutWidget_2)
        self.contacts_state_l2_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.contacts_state_l2_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.contacts_state_l2_frame.setObjectName(_fromUtf8("contacts_state_l2_frame"))
        self.gridLayout_2.addWidget(self.contacts_state_l2_frame, 1, 1, 1, 1)
        self.contacts_state_l3_frame = QtGui.QFrame(self.gridLayoutWidget_2)
        self.contacts_state_l3_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.contacts_state_l3_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.contacts_state_l3_frame.setObjectName(_fromUtf8("contacts_state_l3_frame"))
        self.gridLayout_2.addWidget(self.contacts_state_l3_frame, 2, 1, 1, 1)
        self.gridLayout.addWidget(self.contacts_state, 0, 2, 1, 1)
        self.status = QtGui.QGroupBox(self.gridLayoutWidget)
        self.status.setObjectName(_fromUtf8("status"))
        self.verticalLayoutWidget = QtGui.QWidget(self.status)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, 29, 105, 211))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.status_l1 = QtGui.QPushButton(self.verticalLayoutWidget)
        self.status_l1.setCheckable(True)
        self.status_l1.setObjectName(_fromUtf8("status_l1"))
        self.verticalLayout.addWidget(self.status_l1)
        self.status_l2 = QtGui.QPushButton(self.verticalLayoutWidget)
        self.status_l2.setCheckable(True)
        self.status_l2.setObjectName(_fromUtf8("status_l2"))
        self.verticalLayout.addWidget(self.status_l2)
        self.status_l3 = QtGui.QPushButton(self.verticalLayoutWidget)
        self.status_l3.setCheckable(True)
        self.status_l3.setObjectName(_fromUtf8("status_l3"))
        self.verticalLayout.addWidget(self.status_l3)
        self.reset = QtGui.QPushButton(self.verticalLayoutWidget)
        self.reset.setObjectName(_fromUtf8("reset"))
        self.verticalLayout.addWidget(self.reset)
        self.gridLayout.addWidget(self.status, 0, 0, 1, 1)
        self.trip_group = QtGui.QGroupBox(self.gridLayoutWidget)
        self.trip_group.setObjectName(_fromUtf8("trip_group"))
        self.gridLayoutWidget_3 = QtGui.QWidget(self.trip_group)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 30, 214, 211))
        self.gridLayoutWidget_3.setObjectName(_fromUtf8("gridLayoutWidget_3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.open_l3 = QtGui.QPushButton(self.gridLayoutWidget_3)
        self.open_l3.setObjectName(_fromUtf8("open_l3"))
        self.gridLayout_3.addWidget(self.open_l3, 2, 0, 1, 1)
        self.open_l1 = QtGui.QPushButton(self.gridLayoutWidget_3)
        self.open_l1.setObjectName(_fromUtf8("open_l1"))
        self.gridLayout_3.addWidget(self.open_l1, 0, 0, 1, 1)
        self.close_l2 = QtGui.QPushButton(self.gridLayoutWidget_3)
        self.close_l2.setObjectName(_fromUtf8("close_l2"))
        self.gridLayout_3.addWidget(self.close_l2, 1, 1, 1, 1)
        self.open_l2 = QtGui.QPushButton(self.gridLayoutWidget_3)
        self.open_l2.setObjectName(_fromUtf8("open_l2"))
        self.gridLayout_3.addWidget(self.open_l2, 1, 0, 1, 1)
        self.close_l1 = QtGui.QPushButton(self.gridLayoutWidget_3)
        self.close_l1.setObjectName(_fromUtf8("close_l1"))
        self.gridLayout_3.addWidget(self.close_l1, 0, 1, 1, 1)
        self.close_l3 = QtGui.QPushButton(self.gridLayoutWidget_3)
        self.close_l3.setObjectName(_fromUtf8("close_l3"))
        self.gridLayout_3.addWidget(self.close_l3, 2, 1, 1, 1)
        self.open = QtGui.QPushButton(self.gridLayoutWidget_3)
        self.open.setObjectName(_fromUtf8("open"))
        self.gridLayout_3.addWidget(self.open, 3, 0, 1, 1)
        self.close = QtGui.QPushButton(self.gridLayoutWidget_3)
        self.close.setObjectName(_fromUtf8("close"))
        self.gridLayout_3.addWidget(self.close, 3, 1, 1, 1)
        self.gridLayout.addWidget(self.trip_group, 0, 1, 1, 1)
        self.gridLayout.setColumnMinimumWidth(0, 120)
        self.gridLayout.setColumnMinimumWidth(2, 120)
        self.gridLayout.setColumnStretch(1, 1)

        self.retranslateUi(SwitchAction)
        QtCore.QMetaObject.connectSlotsByName(SwitchAction)

    def retranslateUi(self, SwitchAction):
        SwitchAction.setWindowTitle(_translate("SwitchAction", "Łącznik", None))
        self.contacts_state.setTitle(_translate("SwitchAction", "Stan styków", None))
        self.contacts_state_l1_label.setText(_translate("SwitchAction", "L1", None))
        self.contacts_state_l2_label.setText(_translate("SwitchAction", "L2", None))
        self.contacts_state_l3_label.setText(_translate("SwitchAction", "L3", None))
        self.status.setTitle(_translate("SwitchAction", "Status", None))
        self.status_l1.setText(_translate("SwitchAction", "Status L1", None))
        self.status_l2.setText(_translate("SwitchAction", "Status L2", None))
        self.status_l3.setText(_translate("SwitchAction", "Status L3", None))
        self.reset.setText(_translate("SwitchAction", "Reset ", None))
        self.trip_group.setTitle(_translate("SwitchAction", "Zadziałanie", None))
        self.open_l3.setText(_translate("SwitchAction", "Otwarcie L3", None))
        self.open_l1.setText(_translate("SwitchAction", "Otwarcie L1", None))
        self.close_l2.setText(_translate("SwitchAction", "Zamknięcie L2", None))
        self.open_l2.setText(_translate("SwitchAction", "Otwarcie L2", None))
        self.close_l1.setText(_translate("SwitchAction", "Zamknięcie L1", None))
        self.close_l3.setText(_translate("SwitchAction", "Zamknięcie L3", None))
        self.open.setText(_translate("SwitchAction", "Otwarcie 3f", None))
        self.close.setText(_translate("SwitchAction", "Zamknięcie 3f", None))

